name: FarmCrops
version: 1.1.0
main: dev.samiel.farmcrops.FarmCrops
api-version: 1.20
author: SamielXD
description: Weight-based farming economy plugin with custom crops and statistics

depend: [Vault]
softdepend: [DecentHolograms]

commands:
  sellcrops:
    description: Open the crop selling GUI
    usage: /sellcrops
    aliases: [sell]
  farmstats:
    description: View farm statistics
    usage: /farmstats [player]
  farmtop:
    description: View top farmers
    usage: /farmtop [page]
  farmsettings:
    description: Admin settings
    usage: /farmsettings
    permission: farmcrops.settings
  farmreload:
    description: Reload configuration
    usage: /farmreload
    permission: farmcrops.reload
  farm:
    description: Main menu
    usage: /farm
  farmbackup:
    description: Backup player data
    usage: /farmbackup
    permission: farmcrops.admin
  farmachievements:
    description: View achievements
    usage: /farmachievements
    aliases: [achievements, farmach]
  farmadmin:
    description: Admin panel
    usage: /farmadmin
    permission: farmcrops.admin
  farmgive:
    description: Give custom crop to player
    usage: /farmgive <player> <crop> <weight> <rarity>
    permission: farmcrops.admin

permissions:
  farmcrops.*:
    description: All permissions
    children:
      farmcrops.admin: true
      farmcrops.harvest: true
      farmcrops.sell: true
      farmcrops.stats: true
      farmcrops.top: true
      farmcrops.menu: true
  farmcrops.harvest:
    description: Allow custom crop drops
    default: true
  farmcrops.sell:
    description: Open sell GUI
    default: true
  farmcrops.stats:
    description: View stats
    default: true
  farmcrops.top:
    description: View leaderboard
    default: true
  farmcrops.menu:
    description: Open main menu
    default: true
  farmcrops.admin:
    description: Admin commands
    default: op
  farmcrops.settings:
    description: Settings GUI
    default: op
  farmcrops.reload:
    description: Reload config
    default: op
